name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build-c:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - name: Build with CMake
      working-directory:  ./appC
      run: cmake make
    - name: Upload Artifact
      uses: actions/upload-artifact@main
      with:
        name: compiled-artifact-c
        path: ./appC/bin/*.exe
  build-cpp:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - name: Build with CMake
      working-directory:  ./appCpp
      run: cmake make
    - name: Upload Artifact
      uses: actions/upload-artifact@main
      with:
        name: compiled-artifact-cpp
        path: ./appCpp/bin/*.exe
